import os
import yaml
import uuid
from typing import List
from orchestra.core.enums import AgentRole, OrchestraSection, TaskSeverity
from orchestra.schemas.report import AgentReport
from orchestra.schemas.task import TaskSpec

class Conductor:
    """
    The Conductor receives reports from Agents and converts them into 
    executable Tasks in the Queue.
    """
    
    def __init__(self, queue_dir: str = ".taskmaster/queue"):
        self.queue_dir = queue_dir
        os.makedirs(self.queue_dir, exist_ok=True)

    def receive_report(self, report: AgentReport) -> str:
        """
        Ingests a report and generates a Task Markdown file.
        Returns the Task ID.
        """
        # Logic to determine actual severity/routing could go here.
        # For now, we trust the agent's suggestion but tag it with the Agent's ID.
        
        task_id = f"TASK-{uuid.uuid4().hex[:8].upper()}"
        filename = f"{task_id}_{report.suggested_intent.lower().replace(' ', '_')}.md"
        filepath = os.path.join(self.queue_dir, filename)
        
        # Construct the Task Content
        front_matter = {
            "proposer_id": report.author_role.value,
            "section": report.suggested_target_section.value,
            "severity": report.suggested_severity.value,
            "intent": report.suggested_intent,
            "constraints": ["Generated from Agent Report"],
            "impact": report.summary
        }
        
        body = f"""# Agent Report: {report.author_role.value}
**Timestamp:** {report.timestamp}
**Summary:** {report.summary}

## Details
{report.details}

## Evidence
{', '.join(report.supporting_files)}

---
*Task generated by Conductor.*
"""
        
        # Write to file (Ingestion)
        with open(filepath, "w") as f:
            f.write("---\n")
            yaml.dump(front_matter, f, default_flow_style=False)
            f.write("---\n")
            f.write(body)
            
        print(f"[CONDUCTOR] Processed report from {report.author_role.value}. Created {task_id}.")
        return task_id

    def fill_queue(self, reports: List[AgentReport]):
        """
        Batch processing of reports.
        """
        for report in reports:
            self.receive_report(report)
