import { test, expect } from '@playwright/test';
import path from 'path';
import { startServers } from '../test-helpers';

let helpers: any = null;

test.beforeAll(async () => {
  const repoRoot = path.resolve(__dirname, '..', '..');
  helpers = await startServers(repoRoot);
});

test.afterAll(async () => {
  if (helpers) await helpers.stop();
});

test('sigill artifact links respond with mock artifact payload and new alerts increase count', async ({ page }) => {
  await page.goto(helpers.demoUrl);

  // Ensure there is at least one SIGILL alert from fixtures
  await expect(page.locator('#sigill-count')).toHaveText(/\d+/, { timeout: 15000 });
  const before = Number(await page.locator('#sigill-count').innerText());

  // Get first artifact link if present and validate
  if (before > 0) {
    const firstStrace = await page.locator('.sigill-strace').first();
    const href = await firstStrace.getAttribute('href');
    expect(href).toBeTruthy();

    // Use Playwright request to GET the artifact and assert JSON
    const r = await page.request.get(href as string);
    expect(r.status()).toBe(200);
    const json = await r.json();
    expect(json).toHaveProperty('alertId');
    expect(json).toHaveProperty('file');
  }

  // Now create a new alert using the mock RPC create_alert method
  const rpcBase = `http://127.0.0.1:${helpers.rpcPort}`;
  const newAlert = {
    title: 'SIGILL created by test',
    message: 'Generated by e2e test',
    link: null
  };

  const rpcResp = await page.request.post(`${rpcBase}/rpc`, { data: { jsonrpc: '2.0', method: 'create_alert', params: [newAlert], id: 123 } });
  expect(rpcResp.status()).toBe(200);
  const rpcJson = await rpcResp.json();
  expect(rpcJson.result).toBeTruthy();

  // Reload demo and expect count increased by 1
  await page.goto(helpers.demoUrl);
  await expect(page.locator('#sigill-count')).toHaveText(/\d+/, { timeout: 15000 });
  const after = Number(await page.locator('#sigill-count').innerText());
  expect(after).toBeGreaterThanOrEqual(before + 1);
});