#!/bin/bash
# Quick Start Script for Ralph Extension

echo "==================================="
echo "  Ralph Extension - Quick Start"
echo "==================================="
echo ""
echo "✅ Ralph v0.5.1 is installed and ready!"
echo ""
echo "📋 Quick Actions:"
echo ""
echo "1️⃣  Open Ralph Control Panel:"
echo "   - Click the Ralph icon in VS Code Activity Bar (left sidebar)"
echo "   - OR press Ctrl+Shift+P and type 'Ralph: Open Control Panel'"
echo ""
echo "2️⃣  Test with Sample PRD:"
echo "   - Open PRD.md in the workspace root"
echo "   - Click Start in Ralph Control Panel"
echo "   - Watch Ralph work through the tasks autonomously"
echo ""
echo "3️⃣  Create Your Own PRD:"
echo "   - In Ralph Control Panel, describe what you want to build"
echo "   - Click 'Generate PRD & Tasks'"
echo "   - Click 'Start' to begin development"
echo ""
echo "📚 Documentation:"
echo "   - Full guide: RALPH_SETUP_COMPLETE.md"
echo "   - Sample PRD: PRD.md"
echo "   - GitHub: https://github.com/aymenfurter/ralph"
echo ""
echo "⚙️  Requirements (✅ All Met):"
echo "   ✅ VS Code 1.93+"
echo "   ✅ GitHub Copilot Chat extension"
echo "   ✅ Ralph extension v0.5.1"
echo ""
echo "🎯 Try It Now:"
echo "   code PRD.md"
echo ""
echo "==================================="
