//! Mynta Daemon Manager
//! 
//! Manages the lifecycle of the bundled myntad daemon:
//! - Automatic startup with the wallet
//! - Health monitoring and auto-restart
//! - Graceful shutdown on app exit
//! - Secure configuration management

use std::path::PathBuf;
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;
use std::fs;
use std::io::Write;

use tokio::sync::Mutex as TokioMutex;
use thiserror::Error;
use tokio::sync::mpsc;
use tokio::time::{sleep, timeout};
use tracing::{info, warn, error, debug};

use crate::chain_params::Network;
use crate::rpc::RpcClient;

#[derive(Error, Debug)]
pub enum DaemonError {
    #[error("Daemon binary not found at {0}")]
    BinaryNotFound(PathBuf),
    #[error("Failed to start daemon: {0}")]
    StartFailed(String),
    #[error("Failed to stop daemon: {0}")]
    StopFailed(String),
    #[error("Daemon crashed unexpectedly")]
    Crashed,
    #[error("Configuration error: {0}")]
    ConfigError(String),
    #[error("Data directory error: {0}")]
    DataDirError(String),
    #[error("RPC connection failed after {0} attempts")]
    RpcConnectionFailed(u32),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

/// Daemon status
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DaemonStatus {
    Stopped,
    Starting,
    Running,
    Syncing { progress: f64 },
    Stopping,
    Crashed { error: String },
}

/// Daemon configuration
#[derive(Debug, Clone)]
pub struct DaemonConfig {
    pub network: Network,
    pub data_dir: PathBuf,
    pub rpc_port: u16,
    pub rpc_user: String,
    pub rpc_password: String,
    pub max_connections: u32,
    pub prune: Option<u64>,
    pub txindex: bool,
}

impl DaemonConfig {
    pub fn new(network: Network, base_data_dir: PathBuf) -> Self {
        // Generate secure random credentials
        let rpc_password = generate_secure_password(32);
        
        let data_dir = match network {
            Network::Mainnet => base_data_dir,
            Network::Testnet => base_data_dir.join("testnet3"),
            Network::Regtest => base_data_dir.join("regtest"),
        };

        Self {
            network,
            data_dir,
            rpc_port: network.rpc_port(),
            rpc_user: "myntawallet".to_string(),
            rpc_password,
            max_connections: 125,
            prune: None,
            txindex: true,
        }
    }

    /// Generate mynta.conf content
    pub fn generate_conf(&self) -> String {
        let mut conf = String::new();
        
        conf.push_str("# Mynta configuration - auto-generated by Mynta Wallet\n");
        conf.push_str("# Do not modify while wallet is running\n\n");
        
        // Network
        match self.network {
            Network::Testnet => conf.push_str("testnet=1\n"),
            Network::Regtest => conf.push_str("regtest=1\n"),
            Network::Mainnet => {}
        }
        
        // RPC settings
        conf.push_str("server=1\n");
        conf.push_str(&format!("rpcuser={}\n", self.rpc_user));
        conf.push_str(&format!("rpcpassword={}\n", self.rpc_password));
        conf.push_str(&format!("rpcport={}\n", self.rpc_port));
        conf.push_str("rpcallowip=127.0.0.1\n");
        conf.push_str("rpcbind=127.0.0.1\n");
        
        // Performance settings
        conf.push_str(&format!("maxconnections={}\n", self.max_connections));
        conf.push_str("dbcache=450\n");
        
        // Indexing
        if self.txindex {
            conf.push_str("txindex=1\n");
        }
        
        // Pruning
        if let Some(prune_mb) = self.prune {
            conf.push_str(&format!("prune={}\n", prune_mb));
        }
        
        // Logging
        conf.push_str("printtoconsole=0\n");
        conf.push_str("logtimestamps=1\n");
        
        // Masternode settings (if running a masternode)
        conf.push_str("# Masternode settings (uncomment if running a masternode)\n");
        conf.push_str("# masternode=1\n");
        conf.push_str("# masternodeblsprivkey=YOUR_BLS_PRIVATE_KEY\n");
        
        conf
    }

    /// Write configuration to file
    pub fn write_conf(&self) -> Result<PathBuf, DaemonError> {
        // Create data directory if it doesn't exist
        fs::create_dir_all(&self.data_dir)
            .map_err(|e| DaemonError::DataDirError(e.to_string()))?;

        let conf_path = self.data_dir.join("mynta.conf");
        
        // Only write if doesn't exist or we need to update credentials
        let should_write = if conf_path.exists() {
            // Check if our managed marker exists
            let content = fs::read_to_string(&conf_path).unwrap_or_default();
            content.contains("auto-generated by Mynta Wallet")
        } else {
            true
        };

        if should_write {
            let mut file = fs::File::create(&conf_path)
                .map_err(|e| DaemonError::ConfigError(e.to_string()))?;
            file.write_all(self.generate_conf().as_bytes())
                .map_err(|e| DaemonError::ConfigError(e.to_string()))?;
            
            // Set restrictive permissions on Unix
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let mut perms = fs::metadata(&conf_path)?.permissions();
                perms.set_mode(0o600);
                fs::set_permissions(&conf_path, perms)?;
            }
        }

        Ok(conf_path)
    }
}

/// Inner daemon state
struct DaemonInner {
    config: Option<DaemonConfig>,
    process: Option<Child>,
    shutdown_tx: Option<mpsc::Sender<()>>,
}

/// Daemon manager - handles the myntad process lifecycle
/// Uses Arc internally for safe sharing across async boundaries
#[derive(Clone)]
pub struct DaemonManager {
    inner: Arc<TokioMutex<DaemonInner>>,
    status: Arc<TokioMutex<DaemonStatus>>,
    running: Arc<AtomicBool>,
    binary_path: PathBuf,
}

impl DaemonManager {
    /// Create a new daemon manager
    pub fn new(binary_path: PathBuf) -> Self {
        Self {
            inner: Arc::new(TokioMutex::new(DaemonInner {
                config: None,
                process: None,
                shutdown_tx: None,
            })),
            status: Arc::new(TokioMutex::new(DaemonStatus::Stopped)),
            running: Arc::new(AtomicBool::new(false)),
            binary_path,
        }
    }

    /// Find the daemon binary in various locations
    pub fn find_daemon_binary() -> Option<PathBuf> {
        // Check multiple locations in order of priority
        let candidates = vec![
            // 1. Bundled with app (Tauri resources)
            Self::get_bundled_binary_path(),
            // 2. Same directory as wallet executable
            std::env::current_exe().ok().and_then(|p| {
                p.parent().map(|dir| dir.join("myntad"))
            }),
            // 3. System PATH
            which::which("myntad").ok(),
            // 4. Common installation paths
            Some(PathBuf::from("/usr/local/bin/myntad")),
            Some(PathBuf::from("/usr/bin/myntad")),
            // 5. Development path
            Some(PathBuf::from("/home/kali/Documents/Clone Crypto/Mynta-Final/src/myntad")),
        ];

        for candidate in candidates.into_iter().flatten() {
            if candidate.exists() && candidate.is_file() {
                info!("Found daemon binary at: {:?}", candidate);
                return Some(candidate);
            }
        }

        None
    }

    /// Get the bundled binary path for Tauri
    fn get_bundled_binary_path() -> Option<PathBuf> {
        // In production, Tauri bundles binaries in a specific location
        #[cfg(target_os = "linux")]
        {
            if let Ok(exe) = std::env::current_exe() {
                // AppImage or installed location
                if let Some(dir) = exe.parent() {
                    let bundled = dir.join("myntad");
                    if bundled.exists() {
                        return Some(bundled);
                    }
                    // Also check lib directory for AppImage
                    let lib_bundled = dir.join("lib").join("myntad");
                    if lib_bundled.exists() {
                        return Some(lib_bundled);
                    }
                }
            }
        }

        #[cfg(target_os = "windows")]
        {
            if let Ok(exe) = std::env::current_exe() {
                if let Some(dir) = exe.parent() {
                    let bundled = dir.join("myntad.exe");
                    if bundled.exists() {
                        return Some(bundled);
                    }
                }
            }
        }

        #[cfg(target_os = "macos")]
        {
            if let Ok(exe) = std::env::current_exe() {
                // macOS app bundle: Contents/MacOS/myntad
                if let Some(dir) = exe.parent() {
                    let bundled = dir.join("myntad");
                    if bundled.exists() {
                        return Some(bundled);
                    }
                    // Also check Resources
                    if let Some(contents) = dir.parent() {
                        let resources = contents.join("Resources").join("myntad");
                        if resources.exists() {
                            return Some(resources);
                        }
                    }
                }
            }
        }

        None
    }

    /// Get the default data directory
    pub fn get_default_data_dir() -> PathBuf {
        #[cfg(target_os = "linux")]
        {
            dirs::home_dir()
                .unwrap_or_else(|| PathBuf::from("."))
                .join(".mynta")
        }

        #[cfg(target_os = "windows")]
        {
            dirs::data_local_dir()
                .or_else(dirs::home_dir)
                .unwrap_or_else(|| PathBuf::from("."))
                .join("Mynta")
        }

        #[cfg(target_os = "macos")]
        {
            dirs::data_local_dir()
                .or_else(dirs::home_dir)
                .unwrap_or_else(|| PathBuf::from("."))
                .join("Mynta")
        }

        #[cfg(not(any(target_os = "linux", target_os = "windows", target_os = "macos")))]
        {
            dirs::home_dir()
                .unwrap_or_else(|| PathBuf::from("."))
                .join(".mynta")
        }
    }

    /// Get current status
    pub async fn status(&self) -> DaemonStatus {
        self.status.lock().await.clone()
    }

    /// Check if daemon is running
    pub fn is_running(&self) -> bool {
        self.running.load(Ordering::SeqCst)
    }

    /// Get binary path
    pub fn binary_path(&self) -> &PathBuf {
        &self.binary_path
    }

    /// Start the daemon using cookie authentication (no config file writing)
    pub async fn start(&self, network: Network) -> Result<(), DaemonError> {
        // Check if already running (internal state)
        if self.is_running() {
            info!("Daemon already running");
            return Ok(());
        }

        // Verify binary exists
        if !self.binary_path.exists() {
            return Err(DaemonError::BinaryNotFound(self.binary_path.clone()));
        }

        // Get data directory - use standard Mynta location
        let base_data_dir = Self::get_default_data_dir();
        let data_dir = match network {
            Network::Mainnet => base_data_dir.clone(),
            Network::Testnet => base_data_dir.join("testnet3"),
            Network::Regtest => base_data_dir.join("regtest"),
        };
        
        // Create data directory if needed
        fs::create_dir_all(&data_dir)
            .map_err(|e| DaemonError::DataDirError(e.to_string()))?;

        let rpc_port = network.rpc_port();
        let p2p_port = network.p2p_port();

        // Check if a daemon is already running on this port (external process)
        let cookie_path = data_dir.join(".cookie");
        if cookie_path.exists() {
            info!("Found existing cookie file, checking if daemon is already running...");
            if let Ok(cookie) = fs::read_to_string(&cookie_path) {
                let parts: Vec<&str> = cookie.trim().split(':').collect();
                if parts.len() == 2 {
                    let rpc = crate::rpc::RpcClient::new();
                    let test_config = crate::rpc::ConnectionConfig {
                        host: "127.0.0.1".to_string(),
                        port: rpc_port,
                        username: parts[0].to_string(),
                        password: parts[1].to_string(),
                        network,
                    };
                    rpc.connect(test_config);
                    
                    if let Ok(_info) = rpc.get_network_info().await {
                        info!("External daemon already running on port {}, connecting to it", rpc_port);
                        
                        // Mark as running without starting a new process
                        let config = DaemonConfig {
                            network,
                            data_dir: data_dir.clone(),
                            rpc_port,
                            rpc_user: parts[0].to_string(),
                            rpc_password: parts[1].to_string(),
                            max_connections: 125,
                            prune: None,
                            txindex: true,
                        };
                        
                        {
                            let mut inner = self.inner.lock().await;
                            inner.config = Some(config.clone());
                            // No process - we're connecting to an external one
                            inner.process = None;
                        }
                        self.running.store(true, Ordering::SeqCst);
                        *self.status.lock().await = DaemonStatus::Running;
                        
                        // Start a monitoring task that checks RPC connectivity
                        self.spawn_external_monitor(config);
                        
                        return Ok(());
                    }
                }
            }
        }

        *self.status.lock().await = DaemonStatus::Starting;
        info!("Starting Mynta daemon for {:?} network", network);

        // Build command arguments - use explicit args, rely on cookie auth
        // This avoids writing config files and uses the daemon's native defaults
        let mut args = vec![
            format!("-datadir={}", base_data_dir.display()),
            "-server=1".to_string(),
            "-rpcbind=127.0.0.1".to_string(),
            "-rpcallowip=127.0.0.1".to_string(),
            format!("-rpcport={}", rpc_port),
            format!("-port={}", p2p_port),
            "-printtoconsole=0".to_string(),
            "-daemon=0".to_string(), // We manage the process ourselves
            "-txindex=1".to_string(),
        ];

        // Add network flag
        match network {
            Network::Testnet => args.push("-testnet".to_string()),
            Network::Regtest => args.push("-regtest".to_string()),
            Network::Mainnet => {}
        }

        info!("Daemon args: {:?}", args);

        // Start the process
        let child = Command::new(&self.binary_path)
            .args(&args)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| DaemonError::StartFailed(e.to_string()))?;

        let pid = child.id();
        info!("Daemon started with PID: {}", pid);

        // Create a minimal config for internal tracking (used for RPC connection)
        let config = DaemonConfig {
            network,
            data_dir: data_dir.clone(),
            rpc_port,
            rpc_user: String::new(),     // Will use cookie auth
            rpc_password: String::new(), // Will use cookie auth
            max_connections: 125,
            prune: None,
            txindex: true,
        };

        // Store state
        {
            let mut inner = self.inner.lock().await;
            inner.process = Some(child);
            inner.config = Some(config.clone());
        }
        self.running.store(true, Ordering::SeqCst);

        // Start health monitor
        let (shutdown_tx, shutdown_rx) = mpsc::channel(1);
        {
            let mut inner = self.inner.lock().await;
            inner.shutdown_tx = Some(shutdown_tx);
        }

        // Wait for cookie file and read credentials
        let cookie_path = data_dir.join(".cookie");
        let (rpc_user, rpc_password) = self.wait_for_cookie_auth(&cookie_path, rpc_port).await?;
        
        // Update config with cookie credentials
        {
            let mut inner = self.inner.lock().await;
            if let Some(ref mut cfg) = inner.config {
                cfg.rpc_user = rpc_user.clone();
                cfg.rpc_password = rpc_password.clone();
            }
        }

        let updated_config = DaemonConfig {
            network,
            data_dir,
            rpc_port,
            rpc_user,
            rpc_password,
            max_connections: 125,
            prune: None,
            txindex: true,
        };

        self.spawn_health_monitor(updated_config, shutdown_rx);

        *self.status.lock().await = DaemonStatus::Running;
        info!("Daemon is now running and accepting RPC connections");

        Ok(())
    }
    
    /// Wait for the cookie file to be created and read the credentials
    async fn wait_for_cookie_auth(&self, cookie_path: &std::path::Path, port: u16) -> Result<(String, String), DaemonError> {
        info!("Waiting for cookie auth file at {:?}", cookie_path);
        
        let max_attempts = 60;
        for attempt in 1..=max_attempts {
            if attempt % 5 == 0 {
                info!("Waiting for daemon cookie file... attempt {}/{}", attempt, max_attempts);
            }
            
            if cookie_path.exists() {
                match fs::read_to_string(cookie_path) {
                    Ok(cookie) => {
                        let parts: Vec<&str> = cookie.trim().split(':').collect();
                        if parts.len() == 2 {
                            info!("Cookie auth file read successfully");
                            
                            // Verify RPC is actually responding
                            let rpc = crate::rpc::RpcClient::new();
                            rpc.connect(crate::rpc::ConnectionConfig {
                                host: "127.0.0.1".to_string(),
                                port,
                                username: parts[0].to_string(),
                                password: parts[1].to_string(),
                                network: Network::Mainnet,
                            });
                            
                            match rpc.get_blockchain_info().await {
                                Ok(_) => {
                                    info!("RPC connection established");
                                    return Ok((parts[0].to_string(), parts[1].to_string()));
                                }
                                Err(_) => {
                                    // Cookie exists but RPC not ready yet
                                }
                            }
                        }
                    }
                    Err(e) => {
                        warn!("Could not read cookie file: {}", e);
                    }
                }
            }
            
            // Check if process is still running
            {
                let mut inner = self.inner.lock().await;
                if let Some(ref mut child) = inner.process {
                    match child.try_wait() {
                        Ok(Some(status)) => {
                            error!("Daemon exited prematurely with status: {}", status);
                            *self.status.lock().await = DaemonStatus::Crashed {
                                error: format!("Daemon exited with status: {}", status),
                            };
                            self.running.store(false, Ordering::SeqCst);
                            return Err(DaemonError::Crashed);
                        }
                        Ok(None) => {} // Still running
                        Err(e) => {
                            warn!("Failed to check daemon status: {}", e);
                        }
                    }
                }
            }
            
            sleep(Duration::from_secs(1)).await;
        }
        
        Err(DaemonError::RpcConnectionFailed(max_attempts))
    }

    /// Spawn background health monitor
    fn spawn_health_monitor(&self, config: DaemonConfig, mut shutdown_rx: mpsc::Receiver<()>) {
        let inner = self.inner.clone();
        let status = self.status.clone();
        let running = self.running.clone();

        tokio::spawn(async move {
            let rpc = RpcClient::new();
            rpc.connect(crate::rpc::ConnectionConfig {
                host: "127.0.0.1".to_string(),
                port: config.rpc_port,
                username: config.rpc_user.clone(),
                password: config.rpc_password.clone(),
                network: config.network,
            });

            loop {
                tokio::select! {
                    _ = shutdown_rx.recv() => {
                        info!("Health monitor shutting down");
                        break;
                    }
                    _ = sleep(Duration::from_secs(5)) => {
                        // Check process status
                        let mut inner_guard = inner.lock().await;
                        if let Some(ref mut child) = inner_guard.process {
                            match child.try_wait() {
                                Ok(Some(exit_status)) => {
                                    error!("Daemon process exited: {}", exit_status);
                                    *status.lock().await = DaemonStatus::Crashed {
                                        error: format!("Process exited: {}", exit_status),
                                    };
                                    running.store(false, Ordering::SeqCst);
                                    break;
                                }
                                Ok(None) => {
                                    // Process still running, check sync status
                                    drop(inner_guard); // Release lock before async call
                                    if let Ok(info) = rpc.get_blockchain_info().await {
                                        let progress = info.verificationprogress;
                                        if progress < 0.9999 {
                                            *status.lock().await = DaemonStatus::Syncing { progress };
                                        } else {
                                            *status.lock().await = DaemonStatus::Running;
                                        }
                                    }
                                }
                                Err(e) => {
                                    warn!("Error checking daemon status: {}", e);
                                }
                            }
                        } else {
                            // No process
                            *status.lock().await = DaemonStatus::Stopped;
                            running.store(false, Ordering::SeqCst);
                            break;
                        }
                    }
                }
            }
        });
    }

    /// Spawn a monitor for an external daemon (one we didn't start)
    fn spawn_external_monitor(&self, config: DaemonConfig) {
        let status = self.status.clone();
        let running = self.running.clone();

        tokio::spawn(async move {
            let rpc = RpcClient::new();
            rpc.connect(crate::rpc::ConnectionConfig {
                host: "127.0.0.1".to_string(),
                port: config.rpc_port,
                username: config.rpc_user.clone(),
                password: config.rpc_password.clone(),
                network: config.network,
            });

            let mut consecutive_failures = 0;

            loop {
                sleep(Duration::from_secs(5)).await;
                
                // Check if external daemon is still responding
                match rpc.get_blockchain_info().await {
                    Ok(info) => {
                        consecutive_failures = 0;
                        let progress = info.verificationprogress;
                        if progress < 0.9999 {
                            *status.lock().await = DaemonStatus::Syncing { progress };
                        } else {
                            *status.lock().await = DaemonStatus::Running;
                        }
                    }
                    Err(_) => {
                        consecutive_failures += 1;
                        if consecutive_failures >= 3 {
                            warn!("External daemon no longer responding, marking as stopped");
                            *status.lock().await = DaemonStatus::Stopped;
                            running.store(false, Ordering::SeqCst);
                            break;
                        }
                    }
                }
            }
        });
    }

    /// Stop the daemon gracefully
    pub async fn stop(&self) -> Result<(), DaemonError> {
        if !self.is_running() {
            return Ok(());
        }

        *self.status.lock().await = DaemonStatus::Stopping;
        info!("Stopping Mynta daemon...");

        // Signal health monitor to stop
        {
            let mut inner = self.inner.lock().await;
            if let Some(tx) = inner.shutdown_tx.take() {
                let _ = tx.send(()).await;
            }
        }

        // Try graceful shutdown via RPC first
        let config_opt = {
            let inner = self.inner.lock().await;
            inner.config.clone()
        };

        if let Some(config) = config_opt {
            let rpc = RpcClient::new();
            rpc.connect(crate::rpc::ConnectionConfig {
                host: "127.0.0.1".to_string(),
                port: config.rpc_port,
                username: config.rpc_user.clone(),
                password: config.rpc_password.clone(),
                network: config.network,
            });

            if let Ok(_) = timeout(Duration::from_secs(5), rpc.stop()).await {
                info!("Sent stop command via RPC");
            }
        }

        // Wait for process to exit
        for _ in 0..30 {
            let mut inner = self.inner.lock().await;
            if let Some(ref mut child) = inner.process {
                match child.try_wait() {
                    Ok(Some(_)) => {
                        info!("Daemon stopped gracefully");
                        inner.process = None;
                        self.running.store(false, Ordering::SeqCst);
                        *self.status.lock().await = DaemonStatus::Stopped;
                        return Ok(());
                    }
                    Ok(None) => {
                        drop(inner);
                        sleep(Duration::from_secs(1)).await;
                    }
                    Err(e) => {
                        warn!("Error waiting for daemon: {}", e);
                        break;
                    }
                }
            } else {
                break;
            }
        }

        // Force kill if still running
        {
            let mut inner = self.inner.lock().await;
            if let Some(ref mut child) = inner.process {
                warn!("Daemon didn't stop gracefully, forcing kill...");
                if let Err(e) = child.kill() {
                    error!("Failed to kill daemon: {}", e);
                    return Err(DaemonError::StopFailed(e.to_string()));
                }
                let _ = child.wait();
            }
            inner.process = None;
        }

        self.running.store(false, Ordering::SeqCst);
        *self.status.lock().await = DaemonStatus::Stopped;
        
        info!("Daemon stopped");
        Ok(())
    }

    /// Get RPC connection config for the running daemon
    pub async fn get_rpc_config(&self) -> Option<crate::rpc::ConnectionConfig> {
        let inner = self.inner.lock().await;
        inner.config.as_ref().map(|c| crate::rpc::ConnectionConfig {
            host: "127.0.0.1".to_string(),
            port: c.rpc_port,
            username: c.rpc_user.clone(),
            password: c.rpc_password.clone(),
            network: c.network,
        })
    }
}

/// Generate a cryptographically secure password
fn generate_secure_password(length: usize) -> String {
    use std::iter;
    use rand::Rng;
    
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = rand::thread_rng();
    
    iter::repeat_with(|| {
        let idx = rng.gen_range(0..CHARSET.len());
        CHARSET[idx] as char
    })
    .take(length)
    .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_generation() {
        let config = DaemonConfig::new(Network::Mainnet, PathBuf::from("/tmp/test"));
        let conf = config.generate_conf();
        
        assert!(conf.contains("server=1"));
        assert!(conf.contains(&format!("rpcuser={}", config.rpc_user)));
        assert!(conf.contains(&format!("rpcport={}", config.rpc_port)));
    }

    #[test]
    fn test_password_generation() {
        let pass1 = generate_secure_password(32);
        let pass2 = generate_secure_password(32);
        
        assert_eq!(pass1.len(), 32);
        assert_ne!(pass1, pass2); // Should be different each time
    }
}
