[dependencies.wasm-project]
default-features = false
features = [
    "frontier",
    "native-real-vm-adapters",
]
package = "x3-chain-runtime"
path = "/work/runtime"

[lib]
crate-type = ["cdylib"]
name = "x3_chain_runtime"

[package]
edition = "2021"
name = "x3-chain-runtime-wasm"
version = "1.0.0"

[patch.crates-io.ahash]
path = "/work/patches/ahash"

[patch.crates-io.ar_archive_writer]
path = "/work/patches/ar_archive_writer"

[patch.crates-io.environmental]
path = "/work/patches/environmental"

[patch.crates-io.errno]
path = "/work/patches/errno"

[patch.crates-io.fastbloom]
path = "/work/patches/fastbloom"

[patch.crates-io.getrandom]
path = "/work/patches/getrandom"

[patch.crates-io.home]
path = "/work/patches/home"

[patch.crates-io.icu_properties]
path = "/work/patches/icu_properties_stub"

[patch.crates-io.idna_adapter]
path = "/work/patches/idna_adapter"

[patch.crates-io.jobserver]
path = "/work/patches/jobserver"

[patch.crates-io.memfd]
path = "/work/patches/memfd"

[patch.crates-io.pallet-aura]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.parity-wasm]
path = "/work/patches/parity-wasm"

[patch.crates-io.quinn-proto]
path = "/work/patches/quinn-proto"

[patch.crates-io.rand_core]
path = "/work/patches/rand_core"

[patch.crates-io.sc-client-api]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sc-service]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-application-crypto]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-debug-derive]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-externalities]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-inherents]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-io]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-runtime]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-runtime-interface]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-runtime-interface-proc-macro]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-std]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-storage]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-tracing]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.sp-wasm-interface]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch.crates-io.substrate-prometheus-endpoint]
path = "/work/patches/substrate-prometheus-endpoint"

[patch.crates-io.tempfile]
path = "/work/patches/tempfile"

[patch.crates-io.uuid]
path = "/work/patches/uuid"

[patch.crates-io.wasm-instrument]
path = "/work/patches/wasm-instrument"

[patch."https://github.com/paritytech/polkadot-sdk".frame-support]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".frame-system]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-api]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-application-crypto]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-arithmetic]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-core]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-externalities]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-io]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-runtime]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-runtime-interface]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-std]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-storage]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/polkadot-sdk".sp-weights]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/paritytech/substrate".sc-executor]
path = "/work/patches/sc-executor"

[patch."https://github.com/paritytech/substrate".substrate-prometheus-endpoint]
path = "/work/patches/substrate-prometheus-endpoint"

[patch."https://github.com/polkadot-evm/frontier".sp-core]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/polkadot-evm/frontier".sp-io]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/polkadot-evm/frontier".sp-runtime]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[patch."https://github.com/polkadot-evm/frontier".sp-std]
git = "https://github.com/paritytech/substrate"
rev = "948fbd2"

[profile.dev]
panic = "abort"

[profile.production]
codegen-units = 1
inherits = "release"
lto = "fat"

[profile.release]
lto = "thin"
panic = "abort"

[workspace]
