"""initial

Revision ID: 001_initial
Revises:
Create Date: 2025-12-19 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_contributor_id'), 'allocations', ['contributor_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('wallet', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_contributor_id'), 'claims', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_claims_wallet'), 'claims', ['wallet'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('wallet', sa.String(length=128), nullable=True),
    sa.Column('kyc', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_contributor_id'), 'consents', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_consents_wallet'), 'consents', ['wallet'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('kyc_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('wallet', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('ref', sa.String(length=256), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verifier', sa.String(length=128), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_entries_contributor_id'), 'kyc_entries', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_kyc_entries_wallet'), 'kyc_entries', ['wallet'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(length=256), nullable=True),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('wallet', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('approvals', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('payouts_finalized',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(length=256), nullable=True),
    sa.Column('contributor_id', sa.String(length=128), nullable=True),
    sa.Column('wallet', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts_finalized')
    op.drop_table('pending_actions')
    op.drop_table('kyc_entries')
    op.drop_table('events')
    op.drop_table('consents')
    op.drop_table('claims')
    op.drop_table('audit_log')
    op.drop_table('allocations')
    op.drop_table('admins')
    # ### end Alembic commands ###