#![cfg_attr(not(feature = "std"), no_std)]
#![recursion_limit = "256"]

// Required for impl_runtime_apis! macro in no_std
#[cfg(not(feature = "std"))]
extern crate alloc;

use codec::{Decode, Encode};
pub use frame_support::{
    construct_runtime, parameter_types,
    traits::{ConstBool, ConstU16, ConstU32, ConstU64, ConstU8, Everything, Get},
    weights::{
        constants::{
            BlockExecutionWeight, ExtrinsicBaseWeight, RocksDbWeight, WEIGHT_REF_TIME_PER_SECOND,
        },
        ConstantMultiplier, IdentityFee,
    },
};
use frame_support::{traits::Currency, weights::Weight};
use frame_system::limits;
use pallet_atlas_kernel;
use pallet_atomic_trade_engine;
use pallet_aura;
use pallet_balances;
use pallet_collective;
use pallet_grandpa;
#[cfg(feature = "dev")]
use pallet_sudo;
use pallet_timestamp;
use pallet_transaction_payment::CurrencyAdapter;
use scale_info::TypeInfo;
use sp_api::impl_runtime_apis;
use sp_core::{OpaqueMetadata, H256, U256};
use sp_runtime::{
    create_runtime_str, generic, impl_opaque_keys,
    traits::{AccountIdLookup, BlakeTwo256, Block as BlockT, IdentifyAccount, Verify},
    MultiAddress, MultiSignature, Perbill,
};
use sp_session::{GetSessionNumber, GetValidatorCount};
use sp_std::prelude::*;

mod precompiles;
use precompiles::FrontierPrecompiles;

#[cfg(any(feature = "std", test))]
pub use sp_runtime::BuildStorage;

// WASM binary generated by substrate-wasm-builder
// In native builds with `skip-wasm-build`, we intentionally skip embedding
// the WASM blob and expose an empty binary instead to avoid build failures.
#[cfg(all(feature = "std", not(feature = "skip-wasm-build")))]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

// When building without std OR when explicitly skipping the WASM build,
// provide empty binaries so native builds can proceed without a runtime blob.
#[cfg(any(not(feature = "std"), feature = "skip-wasm-build"))]
pub const WASM_BINARY: Option<&[u8]> = None;
#[cfg(any(not(feature = "std"), feature = "skip-wasm-build"))]
pub const WASM_BINARY_BLOATY: Option<&[u8]> = None;

/// Opaque types used by the CLI commands.
pub mod opaque {
    use super::*;

    pub type BlockNumber = super::BlockNumber;
    pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
    pub type UncheckedExtrinsic = sp_runtime::OpaqueExtrinsic;
    pub type Block = generic::Block<Header, UncheckedExtrinsic>;
    pub type BlockId = generic::BlockId<Block>;
}

pub type BlockNumber = u32;
pub type Index = u32;
/// Alias to 512-bit hash when used in the context of a transaction signature on the chain.
pub type Nonce = Index;
pub type Signature = MultiSignature;
pub type Hash = H256;
pub type Moment = u64;
pub type Balance = u128;
pub type AssetId = u32;
pub type AtlasId = H256;
pub type Address = MultiAddress<AccountId, ()>;
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;

pub const MILLISECS_PER_BLOCK: u64 = 6_000;

pub struct RuntimeVersion;
impl frame_support::traits::Get<sp_version::RuntimeVersion> for RuntimeVersion {
    fn get() -> sp_version::RuntimeVersion {
        VERSION
    }
}
pub const SLOT_DURATION: u64 = MILLISECS_PER_BLOCK;

pub const NANO_ATLAS: Balance = 1;
pub const MICRO_ATLAS: Balance = 1_000 * NANO_ATLAS;
pub const MILLI_ATLAS: Balance = 1_000 * MICRO_ATLAS;
pub const ATLAS: Balance = 1_000 * MILLI_ATLAS;
pub const NATIVE_GAS_PRICE: u64 = 1_000_000_000;

pub const VERSION: sp_version::RuntimeVersion = sp_version::RuntimeVersion {
    spec_name: create_runtime_str!("atlas-sphere"),
    impl_name: create_runtime_str!("atlas-sphere"),
    authoring_version: 1,
    spec_version: 1,
    impl_version: 1,
    apis: RUNTIME_API_VERSIONS,
    transaction_version: 1,
    state_version: 1,
};

parameter_types! {
    pub const BlockHashCount: BlockNumber = 2_400;
    pub const SS58Prefix: u16 = 42;
    pub const MinimumPeriod: Moment = (MILLISECS_PER_BLOCK / 2) as Moment;
    pub const ExistentialDeposit: Balance = 100 * MICRO_ATLAS;
    pub const TransactionByteFee: Balance = 10 * MICRO_ATLAS;
    pub const MaxAssetsPerAccount: u32 = 32;
    pub const MaxAssetSymbolLength: u32 = 16;
    pub const MaxPayloadLength: u32 = 32 * 1024;
    pub const MaxEvmPayloadLength: u32 = 16 * 1024;  // 16 KB for EVM payloads
    pub const MaxSvmPayloadLength: u32 = 16 * 1024;  // 16 KB for SVM payloads
    pub const MaxCombinedPayloadLength: u32 = 32 * 1024;  // 32 KB combined limit
    pub const MaxAuthorities: u32 = 100;  // Maximum 100 authorities
    pub const MinAuthorities: u32 = 1;  // Minimum 1 authority required
    pub const DefaultEvmGasLimit: u64 = 10_000_000;  // 10M gas for EVM
    pub const DefaultSvmComputeLimit: u64 = 200_000;  // 200k compute units for SVM
    pub BlockWeights: limits::BlockWeights = limits::BlockWeights::with_sensible_defaults(
        Weight::from_parts(12 * WEIGHT_REF_TIME_PER_SECOND, 5 * 1024 * 1024),
        Perbill::from_percent(75),
    );
    pub BlockLength: limits::BlockLength = limits::BlockLength::max_with_normal_ratio(
        5 * 1024 * 1024,
        Perbill::from_percent(75),
    );
}

parameter_types! {
    pub const ChainId: u64 = 650_000;
    pub const GasLimitPovSizeRatio: u64 = 40;
    pub WeightPerGas: Weight = Weight::from_parts(20_000, 0);
}

pub struct BlockGasLimit;
impl Get<U256> for BlockGasLimit {
    fn get() -> U256 {
        U256::from(30_000_000u64)
    }
}

pub struct PrecompilesValue;
impl Get<FrontierPrecompiles<Runtime>> for PrecompilesValue {
    fn get() -> FrontierPrecompiles<Runtime> {
        FrontierPrecompiles::new()
    }
}

#[cfg(feature = "std")]
pub fn native_version() -> sp_version::NativeVersion {
    sp_version::NativeVersion {
        runtime_version: VERSION,
        can_author_with: Default::default(),
    }
}

parameter_types! {
    pub const MaxSetIdSessionEntries: u64 = 0;
    pub const OperationalFeeMultiplier: u8 = 5;
}

parameter_types! {
    pub const CouncilMotionDuration: BlockNumber = 3 * 24 * 60 * 60 / (MILLISECS_PER_BLOCK as BlockNumber / 1000);
    pub const CouncilMaxProposals: u32 = 100;
    pub const CouncilMaxMembers: u32 = 100;
    pub MaxProposalWeight: Weight = Perbill::from_percent(50) * BlockWeights::get().max_block;
}

#[cfg(feature = "dev")]
construct_runtime!(
    pub enum Runtime where
        Block = Block,
        NodeBlock = Block,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        System: frame_system,
        Timestamp: pallet_timestamp,
        Aura: pallet_aura,
        Grandpa: pallet_grandpa,
        Balances: pallet_balances,
        TransactionPayment: pallet_transaction_payment,
        EVM: pallet_evm,
        AtlasKernel: pallet_atlas_kernel,
        AtomicTradeEngine: pallet_atomic_trade_engine,
        Council: pallet_collective::<Instance1>,
        Sudo: pallet_sudo,
    }
);

#[cfg(not(feature = "dev"))]
construct_runtime!(
    pub enum Runtime where
        Block = Block,
        NodeBlock = Block,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        System: frame_system,
        Timestamp: pallet_timestamp,
        Aura: pallet_aura,
        Grandpa: pallet_grandpa,
        Balances: pallet_balances,
        TransactionPayment: pallet_transaction_payment,
        EVM: pallet_evm,
        AtlasKernel: pallet_atlas_kernel,
        AtomicTradeEngine: pallet_atomic_trade_engine,
        Council: pallet_collective::<Instance1>,
    }
);

pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
pub type UncheckedExtrinsic =
    generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
pub type Block = generic::Block<Header, UncheckedExtrinsic>;
pub type Executive = frame_executive::Executive<
    Runtime,
    Block,
    frame_system::ChainContext<Runtime>,
    Runtime,
    AllPalletsWithSystem,
>;

impl_opaque_keys! {
    pub struct SessionKeys {
        pub aura: Aura,
    }
}

pub type SignedExtra = (
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
);

pub type SignedPayload = generic::SignedPayload<RuntimeCall, SignedExtra>;

// ===== Config Impls (after construct_runtime!) =====

type NegativeImbalance = <Balances as Currency<AccountId>>::NegativeImbalance;

pub struct DealWithFees;
impl frame_support::traits::OnUnbalanced<NegativeImbalance> for DealWithFees {
    fn on_unbalanced(amount: NegativeImbalance) {
        drop(amount);
    }
}

pub struct FixedGasPrice;
impl pallet_evm::FeeCalculator for FixedGasPrice {
    fn min_gas_price() -> (U256, Weight) {
        (U256::from(NATIVE_GAS_PRICE), Weight::zero())
    }
}

impl frame_system::Config for Runtime {
    type BaseCallFilter = Everything;
    type Block = Block;
    type BlockWeights = BlockWeights;
    type BlockLength = BlockLength;
    type DbWeight = RocksDbWeight;
    type RuntimeOrigin = RuntimeOrigin;
    type RuntimeCall = RuntimeCall;
    type Hash = Hash;
    type Hashing = BlakeTwo256;
    type AccountId = AccountId;
    type Lookup = AccountIdLookup<AccountId, ()>;
    type RuntimeEvent = RuntimeEvent;
    type BlockHashCount = BlockHashCount;
    type Version = RuntimeVersion;
    type PalletInfo = PalletInfo;
    type AccountData = pallet_balances::AccountData<Balance>;
    type OnNewAccount = ();
    type OnKilledAccount = ();
    type SystemWeightInfo = frame_system::weights::SubstrateWeight<Runtime>;
    type SS58Prefix = ConstU16<42>;
    type OnSetCode = ();
    type MaxConsumers = ConstU32<16>;
    type Nonce = Index;
}

impl pallet_timestamp::Config for Runtime {
    type Moment = Moment;
    type OnTimestampSet = ();
    type MinimumPeriod = MinimumPeriod;
    type WeightInfo = ();
}

impl pallet_aura::Config for Runtime {
    type AuthorityId = sp_consensus_aura::sr25519::AuthorityId;
    type MaxAuthorities = MaxAuthorities;
    type DisabledValidators = ();
    type AllowMultipleBlocksPerSlot = ConstBool<false>;
}

impl pallet_grandpa::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type KeyOwnerProof = SessionHandler;
    type EquivocationReportSystem = ();
    type WeightInfo = ();
    type MaxAuthorities = MaxAuthorities;
    type MaxSetIdSessionEntries = MaxSetIdSessionEntries;
}

impl pallet_balances::Config for Runtime {
    type Balance = Balance;
    type DustRemoval = ();
    type RuntimeEvent = RuntimeEvent;
    type ExistentialDeposit = ExistentialDeposit;
    type AccountStore = System;
    type MaxLocks = ConstU32<50>;
    type MaxReserves = ConstU32<50>;
    type MaxHolds = ConstU32<0>;
    type MaxFreezes = ConstU32<0>;
    type ReserveIdentifier = [u8; 8];
    type FreezeIdentifier = ();
    type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;
    type RuntimeHoldReason = ();
}

impl pallet_transaction_payment::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type OnChargeTransaction = CurrencyAdapter<Balances, DealWithFees>;
    type OperationalFeeMultiplier = OperationalFeeMultiplier;
    type WeightToFee = IdentityFee<Balance>;
    type LengthToFee = ConstantMultiplier<Balance, TransactionByteFee>;
    type FeeMultiplierUpdate = ();
}

#[cfg(feature = "dev")]
impl pallet_sudo::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeCall = RuntimeCall;
    type WeightInfo = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

pub type EnsureRootOrHalfCouncil = frame_support::traits::EitherOfDiverse<
    frame_system::EnsureRoot<AccountId>,
    pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 1, 2>,
>;

pub type CouncilCollective = pallet_collective::Instance1;
impl pallet_collective::Config<CouncilCollective> for Runtime {
    type RuntimeOrigin = RuntimeOrigin;
    type Proposal = RuntimeCall;
    type RuntimeEvent = RuntimeEvent;
    type MotionDuration = CouncilMotionDuration;
    type MaxProposals = CouncilMaxProposals;
    type MaxMembers = CouncilMaxMembers;
    type DefaultVote = pallet_collective::PrimeDefaultVote;
    type WeightInfo = pallet_collective::weights::SubstrateWeight<Runtime>;
    type SetMembersOrigin = frame_system::EnsureRoot<AccountId>;
    type MaxProposalWeight = MaxProposalWeight;
}

impl pallet_evm::Config for Runtime {
    type FeeCalculator = FixedGasPrice;
    type GasWeightMapping = pallet_evm::FixedGasWeightMapping<Self>;
    type WeightPerGas = WeightPerGas;
    type BlockHashMapping = pallet_evm::SubstrateBlockHashMapping<Self>;
    type CallOrigin = pallet_evm::EnsureAddressRoot<AccountId>;
    type WithdrawOrigin = pallet_evm::EnsureAddressTruncated;
    type AddressMapping = pallet_evm::HashedAddressMapping<BlakeTwo256>;
    type Currency = Balances;
    type RuntimeEvent = RuntimeEvent;
    type PrecompilesType = FrontierPrecompiles<Self>;
    type PrecompilesValue = PrecompilesValue;
    type ChainId = ChainId;
    type BlockGasLimit = BlockGasLimit;
    type Runner = pallet_evm::runner::stack::Runner<Self>;
    type OnChargeTransaction = pallet_evm::EVMCurrencyAdapter<Balances, ()>;
    type OnCreate = ();
    type FindAuthor = ();
    type GasLimitPovSizeRatio = GasLimitPovSizeRatio;
    type Timestamp = Timestamp;
    type WeightInfo = pallet_evm::weights::SubstrateWeight<Self>;
}

impl pallet_atlas_kernel::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type Balance = Balance;
    type AssetId = AssetId;
    type AtlasId = AtlasId;
    type MaxAssetsPerAccount = MaxAssetsPerAccount;
    type MaxAssetSymbolLength = MaxAssetSymbolLength;
    type MaxEvmPayloadLength = MaxEvmPayloadLength;
    type MaxSvmPayloadLength = MaxSvmPayloadLength;
    type MaxCombinedPayloadLength = MaxCombinedPayloadLength;
    type MaxAuthorities = MaxAuthorities;
    type MinAuthorities = MinAuthorities;
    type DefaultEvmGasLimit = DefaultEvmGasLimit;
    type DefaultSvmComputeLimit = DefaultSvmComputeLimit;
    type WeightInfo = pallet_atlas_kernel::weights::SubstrateWeight<Runtime>;
    type Currency = Balances;
    // VM Adapters: Use real adapters for native runtime, mock for WASM
    // Real adapters wrap Frontier EVM and solana-rbpf for actual execution
    // Mock adapters provide deterministic behavior for testing and WASM builds
    #[cfg(feature = "std")]
    type EvmAdapter = native_vm_adapters::NativeEvmAdapter;
    #[cfg(feature = "std")]
    type SvmAdapter = native_vm_adapters::NativeSvmAdapter;
    #[cfg(not(feature = "std"))]
    type EvmAdapter = pallet_atlas_kernel::MockEvmAdapter;
    #[cfg(not(feature = "std"))]
    type SvmAdapter = pallet_atlas_kernel::MockSvmAdapter;
    type GovernanceOrigin = EnsureRootOrHalfCouncil;
}

// ===== AtomicTradeEngine Configuration =====

parameter_types! {
    pub const MaxTradeLegs: u32 = 16;
    pub const MaxCheckpoints: u32 = 8;
    pub const MaxPendingBatchesPerAccount: u32 = 64;
    pub const DefaultTradeEvmGasLimit: u64 = 500_000;
    pub const DefaultTradeSvmComputeLimit: u64 = 500_000;
}

impl pallet_atomic_trade_engine::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type WeightInfo = pallet_atomic_trade_engine::weights::SubstrateWeight<Runtime>;
    type Currency = Balances;
    // Use the same VM adapters as AtlasKernel
    #[cfg(feature = "std")]
    type EvmAdapter = native_vm_adapters::NativeEvmAdapter;
    #[cfg(feature = "std")]
    type SvmAdapter = native_vm_adapters::NativeSvmAdapter;
    #[cfg(not(feature = "std"))]
    type EvmAdapter = pallet_atlas_kernel::MockEvmAdapter;
    #[cfg(not(feature = "std"))]
    type SvmAdapter = pallet_atlas_kernel::MockSvmAdapter;
    type MaxTradeLegs = MaxTradeLegs;
    type MaxCheckpoints = MaxCheckpoints;
    type MaxPendingBatchesPerAccount = MaxPendingBatchesPerAccount;
    type DefaultTradeEvmGasLimit = DefaultTradeEvmGasLimit;
    type DefaultTradeSvmComputeLimit = DefaultTradeSvmComputeLimit;
    type AmmRegistrarOrigin = EnsureRootOrHalfCouncil;
}

#[cfg(feature = "std")]
mod native_vm_adapters {
    use super::*;
    use atlas_evm_integration::{
        EvmConfig, EvmError, EvmExecutionResult, EvmExecutor, FrontierEvmExecutor,
    };
    use atlas_svm_integration::{
        RbpfSvmExecutor, SvmConfig, SvmError, SvmExecutionResult, SvmExecutor,
    };
    use pallet_atlas_kernel::{
        EvmExecutorAdapter, ExecutionLog, ExecutionReceipt, StateChange, SvmExecutorAdapter,
    };
    use sp_core::H160;
    use sp_runtime::{traits::SaturatedConversion, DispatchError};

    pub struct NativeEvmAdapter;
    pub struct NativeSvmAdapter;

    impl EvmExecutorAdapter for NativeEvmAdapter {
        fn execute(payload: &[u8], gas_limit: u64) -> Result<ExecutionReceipt, DispatchError> {
            let executor = FrontierEvmExecutor::<super::Runtime>::new();
            let config = evm_config(gas_limit);
            let result = executor
                .execute(payload, H160::zero(), None, U256::zero(), &config)
                .map_err(|err| DispatchError::Other(evm_error_str(err)))?;
            Ok(map_evm_receipt(result))
        }

        fn estimate_gas(payload: &[u8]) -> Result<u64, DispatchError> {
            let executor = FrontierEvmExecutor::<super::Runtime>::new();
            let limit = gas_ceiling();
            let config = evm_config(limit);
            executor
                .estimate_gas(payload, H160::zero(), None, U256::zero(), &config)
                .map_err(|_| DispatchError::Other("Gas estimation failed"))
        }

        fn validate(payload: &[u8]) -> Result<(), DispatchError> {
            let executor = FrontierEvmExecutor::<super::Runtime>::new();
            executor
                .validate_bytecode(payload)
                .map_err(|_| DispatchError::Other("Invalid EVM bytecode"))
        }
    }

    impl SvmExecutorAdapter for NativeSvmAdapter {
        fn execute(payload: &[u8], compute_limit: u64) -> Result<ExecutionReceipt, DispatchError> {
            if payload.is_empty() {
                return Err(DispatchError::Other("Empty SVM payload"));
            }

            let executor = RbpfSvmExecutor::new();
            let config = svm_config(compute_limit);
            let result = executor
                .execute_bpf(payload, &[], &config)
                .map_err(|err| DispatchError::Other(svm_error_str(err)))?;
            Ok(map_svm_receipt(result))
        }

        fn validate(payload: &[u8]) -> Result<(), DispatchError> {
            let executor = RbpfSvmExecutor::new();
            executor
                .validate_program(payload)
                .map_err(|err| DispatchError::Other(svm_error_str(err)))
        }
    }

    fn gas_ceiling() -> u64 {
        let limit = super::BlockGasLimit::get();
        if limit > U256::from(u64::MAX) {
            u64::MAX
        } else {
            limit.low_u64()
        }
    }

    fn evm_config(gas_limit: u64) -> EvmConfig {
        let block_number =
            frame_system::Pallet::<super::Runtime>::block_number().saturated_into::<u64>();
        let block_timestamp = pallet_timestamp::Pallet::<super::Runtime>::now();

        EvmConfig {
            gas_limit,
            gas_price: U256::from(super::NATIVE_GAS_PRICE),
            block_number,
            block_timestamp,
            chain_id: super::ChainId::get(),
            base_fee: U256::from(super::NATIVE_GAS_PRICE),
            coinbase: H160::zero(),
        }
    }

    fn svm_config(compute_limit: u64) -> SvmConfig {
        let slot = frame_system::Pallet::<super::Runtime>::block_number().saturated_into::<u64>();
        let ts: i64 = pallet_timestamp::Pallet::<super::Runtime>::now().saturated_into();

        SvmConfig {
            compute_unit_limit: compute_limit,
            compute_unit_price: 1,
            slot,
            block_timestamp: ts,
            recent_blockhash: [0u8; 32],
            enable_cpi: false,
            max_cpi_depth: 0,
        }
    }

    fn map_evm_receipt(result: EvmExecutionResult) -> ExecutionReceipt {
        ExecutionReceipt {
            success: result.success,
            gas_used: result.gas_used,
            return_data: result.output,
            logs: result
                .logs
                .into_iter()
                .map(|log| ExecutionLog {
                    address: log.address.as_bytes().to_vec(),
                    topics: log.topics,
                    data: log.data,
                })
                .collect(),
            state_changes: result
                .state_changes
                .into_iter()
                .map(|change| {
                    let balance_delta = change
                        .balance_delta
                        .unsigned_abs()
                        .min(u128::from(u64::MAX)) as u64;
                    let nonce_delta = change.nonce_delta.unsigned_abs().min(u64::MAX);
                    let default_key = H256::from_low_u64_be(balance_delta);
                    let default_value = H256::from_low_u64_be(nonce_delta);
                    let (key, value) = change
                        .storage_changes
                        .first()
                        .cloned()
                        .unwrap_or((default_key, default_value));

                    StateChange {
                        address: change.address.as_bytes().to_vec(),
                        key,
                        value,
                    }
                })
                .collect(),
        }
    }

    fn map_svm_receipt(result: SvmExecutionResult) -> ExecutionReceipt {
        ExecutionReceipt {
            success: result.success,
            gas_used: result.compute_units_used,
            return_data: result.output,
            logs: result
                .logs
                .into_iter()
                .map(|data| ExecutionLog {
                    address: vec![0u8; 32],
                    topics: Vec::new(),
                    data,
                })
                .collect(),
            state_changes: result
                .account_updates
                .into_iter()
                .map(|update| StateChange {
                    address: update.pubkey.to_vec(),
                    key: H256::from_low_u64_be(update.lamports),
                    value: truncate_to_h256(&update.data),
                })
                .collect(),
        }
    }

    fn truncate_to_h256(data: &[u8]) -> H256 {
        if data.is_empty() {
            return H256::zero();
        }
        let mut buf = [0u8; 32];
        let take = core::cmp::min(32, data.len());
        buf[..take].copy_from_slice(&data[..take]);
        H256::from(buf)
    }

    fn evm_error_str(error: EvmError) -> &'static str {
        match error {
            EvmError::InvalidPayload => "Invalid EVM payload",
            EvmError::ExecutionReverted => "EVM execution reverted",
            EvmError::OutOfGas => "EVM out of gas",
            EvmError::InvalidState => "Invalid EVM state",
            EvmError::StackOverflow => "EVM stack overflow",
            EvmError::StackUnderflow => "EVM stack underflow",
            EvmError::InvalidOpcode(_) => "Invalid EVM opcode",
            EvmError::CreateCollision => "EVM create collision",
            EvmError::ExecutionFailed(_) => "EVM execution failed",
        }
    }

    fn svm_error_str(error: SvmError) -> &'static str {
        match error {
            SvmError::InvalidPayload => "Invalid SVM payload",
            SvmError::ExecutionFailed => "SVM execution failed",
            SvmError::InvalidAccount => "Invalid SVM account",
            SvmError::InvalidSignature => "Invalid SVM signature",
            SvmError::OutOfComputeUnits => "SVM out of compute units",
            SvmError::InvalidInstructionData => "Invalid SVM instruction",
            SvmError::AccountDataTooSmall => "SVM account data too small",
            SvmError::InsufficientFunds => "SVM insufficient funds",
            SvmError::ProgramNotExecutable => "SVM program not executable",
            SvmError::InvalidProgramId => "Invalid SVM program id",
            SvmError::ExecutionError(_) => "SVM execution error",
        }
    }
}
// Session trait implementations for minimal runtime
#[derive(Debug, Clone, Copy, PartialEq, Eq, Encode, Decode, TypeInfo)]
pub struct SessionHandler;

impl GetValidatorCount for SessionHandler {
    fn validator_count(&self) -> u32 {
        0
    }
}

impl GetSessionNumber for SessionHandler {
    fn session(&self) -> u32 {
        0
    }
}

// sp_session::Config not available in polkadot-v1.0.0
// impl sp_session::Config for Runtime {}

// sp_session::SessionKeys trait has incompatible signatures in polkadot-v1.0.0
/*
impl sp_session::SessionKeys<Block> for Runtime {
    fn generate_session_keys(seed: Option<Vec<u8>>) -> Vec<u8> {
        SessionKeys::generate(seed)
    }

    fn decode_session_keys(encoded: Vec<u8>) -> Option<Vec<(Vec<u8>, sp_core::crypto::KeyTypeId)>> {
        SessionKeys::decode_into_raw_public_keys(&encoded)
    }
}
*/

impl_runtime_apis! {
    impl sp_api::Core<Block> for Runtime {
        fn version() -> sp_version::RuntimeVersion {
            VERSION
        }

        fn execute_block(block: Block) {
            Executive::execute_block(block);
        }

        fn initialize_block(header: &<Block as BlockT>::Header) {
            Executive::initialize_block(header);
        }
    }

    impl sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block> for Runtime {
        fn validate_transaction(
            source: sp_runtime::transaction_validity::TransactionSource,
            tx: <Block as BlockT>::Extrinsic,
            block_hash: <Block as BlockT>::Hash,
        ) -> sp_runtime::transaction_validity::TransactionValidity {
            Executive::validate_transaction(source, tx, block_hash)
        }
    }

    impl pallet_atlas_kernel::AtlasKernelRuntimeApi<Block, AccountId, Balance, AssetId> for Runtime {
        fn get_canonical_balance(account: AccountId, asset_id: AssetId) -> Balance {
            pallet_atlas_kernel::CanonicalLedger::<Runtime>::get(&account, &asset_id)
        }

        fn get_asset_metadata(asset_id: AssetId) -> Option<(Vec<u8>, u8)> {
            pallet_atlas_kernel::AssetRegistry::<Runtime>::get(&asset_id)
                .map(|metadata| (metadata.symbol.into_inner(), metadata.decimals))
        }

        fn is_authorized(account: AccountId) -> bool {
            pallet_atlas_kernel::AuthorizedAccounts::<Runtime>::contains_key(&account)
        }

        fn get_authorized_accounts() -> Vec<AccountId> {
            pallet_atlas_kernel::AuthorizedAccounts::<Runtime>::iter_keys().collect()
        }

        fn get_authorities() -> Vec<AccountId> {
            pallet_atlas_kernel::Authorities::<Runtime>::get().into_inner()
        }
    }

    impl pallet_atomic_trade_engine::AtomicTradeEngineApi<Block> for Runtime {
        fn simulate_trade(
            _token_in: sp_core::H256,
            _token_out: sp_core::H256,
            amount_in: u128,
            slippage_bps: u32,
        ) -> pallet_atomic_trade_engine::runtime_api::SimulationResult {
            use pallet_atomic_trade_engine::runtime_api::SimulationResult;

            // Simplified simulation - returns mock data
            // Full implementation would build TradeLegInput and call simulate_trade_path
            let estimated_output = amount_in.saturating_mul(10000 - slippage_bps as u128) / 10000;

            SimulationResult {
                success: true,
                estimated_output,
                price_impact_bps: slippage_bps,
                evm_gas: 150_000,
                svm_compute: 0,
                route: vec![],
                error: None,
            }
        }

        fn estimate_execution_cost(
            legs: u32,
            vm_types: Vec<u8>,
        ) -> (u64, u64) {
            let mut evm_gas: u64 = 0;
            let mut svm_compute: u64 = 0;

            for vm_type in vm_types.iter().take(legs as usize) {
                match vm_type {
                    0 => evm_gas = evm_gas.saturating_add(150_000), // EVM
                    1 => svm_compute = svm_compute.saturating_add(200_000), // SVM
                    2 => { // CrossVM
                        evm_gas = evm_gas.saturating_add(200_000);
                        svm_compute = svm_compute.saturating_add(250_000);
                    }
                    _ => {}
                }
            }

            (evm_gas, svm_compute)
        }

        fn get_price_data(
            token_a: sp_core::H256,
            token_b: sp_core::H256,
        ) -> pallet_atomic_trade_engine::runtime_api::PriceDataResponse {
            use pallet_atomic_trade_engine::runtime_api::PriceDataResponse;

            let twap = pallet_atomic_trade_engine::Pallet::<Runtime>::get_twap(token_a, token_b);
            let latest = pallet_atomic_trade_engine::Pallet::<Runtime>::get_latest_price(token_a, token_b);
            let twap_data = pallet_atomic_trade_engine::TwapData::<Runtime>::get((token_a, token_b));

            PriceDataResponse {
                exists: twap.is_some() || latest.is_some(),
                twap_price: twap,
                latest_price: latest,
                observation_count: twap_data.as_ref().map(|t| t.observation_count).unwrap_or(0),
                last_updated: twap_data.map(|t| t.last_timestamp).unwrap_or(0),
            }
        }

        fn get_batch_status(batch_hash: sp_core::H256) -> pallet_atomic_trade_engine::runtime_api::BatchStatusResponse {
            use pallet_atomic_trade_engine::runtime_api::BatchStatusResponse;

            let maybe_batch = pallet_atomic_trade_engine::TradeBatches::<Runtime>::get(batch_hash);

            match maybe_batch {
                Some(batch) => BatchStatusResponse {
                    exists: true,
                    status: match batch.status {
                        pallet_atomic_trade_engine::BatchStatus::Pending => 0,
                        pallet_atomic_trade_engine::BatchStatus::Executing => 1,
                        pallet_atomic_trade_engine::BatchStatus::Completed => 2,
                        pallet_atomic_trade_engine::BatchStatus::Failed => 3,
                        pallet_atomic_trade_engine::BatchStatus::Cancelled => 4,
                    },
                    submitted_at: batch.created_at,
                    finalized_at: None, // TradeBatch doesn't track finalized_at
                    legs_executed: batch.legs.len() as u32,
                    checkpoints: 0, // Checkpoints stored separately
                },
                None => BatchStatusResponse::default(),
            }
        }

        fn find_route(
            _token_in: sp_core::H256,
            _token_out: sp_core::H256,
            _amount_in: u128,
        ) -> Option<pallet_atomic_trade_engine::types::TradeRoute> {
            // Route finding requires populated AMM pools
            // Return None until pools are registered
            None
        }

        fn is_authorized(account: Vec<u8>) -> bool {
            // Delegate authorization to Atlas Kernel's authorized accounts
            use codec::Decode;
            if let Ok(account_id) = AccountId::decode(&mut &account[..]) {
                // Check if account is authorized in the main Atlas Kernel pallet
                pallet_atlas_kernel::AuthorizedAccounts::<Runtime>::contains_key(&account_id)
            } else {
                false
            }
        }
    }

    impl sp_consensus_aura::AuraApi<Block, sp_consensus_aura::sr25519::AuthorityId> for Runtime {
        fn slot_duration() -> sp_consensus_aura::SlotDuration {
            sp_consensus_aura::SlotDuration::from_millis(Aura::slot_duration())
        }

        fn authorities() -> Vec<sp_consensus_aura::sr25519::AuthorityId> {
            Aura::authorities().to_vec()
        }
    }

    impl sp_consensus_grandpa::GrandpaApi<Block> for Runtime {
        fn grandpa_authorities() -> sp_consensus_grandpa::AuthorityList {
            Grandpa::grandpa_authorities()
        }

        fn current_set_id() -> sp_consensus_grandpa::SetId {
            Grandpa::current_set_id()
        }

        fn submit_report_equivocation_unsigned_extrinsic(
            _equivocation_proof: sp_consensus_grandpa::EquivocationProof<
                <Block as BlockT>::Hash,
                sp_runtime::traits::NumberFor<Block>,
            >,
            _key_owner_proof: sp_consensus_grandpa::OpaqueKeyOwnershipProof,
        ) -> Option<()> {
            None
        }

        fn generate_key_ownership_proof(
            _set_id: sp_consensus_grandpa::SetId,
            _authority_id: sp_consensus_grandpa::AuthorityId,
        ) -> Option<sp_consensus_grandpa::OpaqueKeyOwnershipProof> {
            None
        }
    }

    impl sp_block_builder::BlockBuilder<Block> for Runtime {
        fn apply_extrinsic(extrinsic: <Block as BlockT>::Extrinsic) -> sp_runtime::ApplyExtrinsicResult {
            Executive::apply_extrinsic(extrinsic)
        }

        fn finalize_block() -> <Block as BlockT>::Header {
            Executive::finalize_block()
        }

        fn inherent_extrinsics(data: sp_inherents::InherentData) -> Vec<<Block as BlockT>::Extrinsic> {
            data.create_extrinsics()
        }

        fn check_inherents(
            block: Block,
            data: sp_inherents::InherentData,
        ) -> sp_inherents::CheckInherentsResult {
            data.check_extrinsics(&block)
        }
    }

    impl frame_system_rpc_runtime_api::AccountNonceApi<Block, AccountId, Nonce> for Runtime {
        fn account_nonce(account: AccountId) -> Nonce {
            System::account_nonce(account)
        }
    }

    impl sp_api::Metadata<Block> for Runtime {
        fn metadata() -> OpaqueMetadata {
            OpaqueMetadata::new(Runtime::metadata().into())
        }

        fn metadata_at_version(version: u32) -> Option<OpaqueMetadata> {
            Runtime::metadata_at_version(version)
        }

        fn metadata_versions() -> sp_std::vec::Vec<u32> {
            Runtime::metadata_versions()
        }
    }
}

#[cfg(feature = "std")]
pub fn atlas_kernel_default_assets() -> Vec<(AssetId, Vec<u8>, u8)> {
    vec![
        (0, b"ATLAS".to_vec(), 12),
        (1, b"ETH".to_vec(), 18),
        (2, b"SOL".to_vec(), 9),
        (3, b"USDC".to_vec(), 6),
    ]
}
