[package]
name = "x3-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
x3-common = { path = "../x3-common" }
x3-ast = { path = "../x3-ast" }
x3-compiler = { path = "../compiler" }
x3-vm = { path = "../vm" }

[[bin]]
name = "run_simple"
path = "src/main.rs"
